WORD_CATEGORIES = {
    "Acción y efecto": {
        "escritura_erronea": ["Acc", "acc y ef", "Acc y ef", "acc y efecto", "Acc y efecto", "Acc y efecto ", "acc y eff", "Acc y eff", "acc/ef", "Accion", "acción", "Acción ", "Acción y efect", "accion y efecto", "Accion y efecto", "acción y efecto", "Acción y efecto", "Acción y Efecto", "Acción y efecto-N", "acción y efecto ", "Acción y efecto ", "Acción y efecto/ Coloquial", "AYF"],
        "comienzo_acepcion": ["Acción de", "Efecto de", "Acción y efecto de", "Acto de"]
    },
    "Adverbio": {
        "escritura_erronea": ["Adbervio", "adeverbio", "adv", "Adv", "adverbio", "Adverbio", "ADverbio", "ADVERBIO", "Adverbio ", "Adverbio - N"]
    },
    "Adjetivo": {
        "escritura_erronea": ["adj", "adj coloq", "Adj.", "adjetivo", "aDJEtivo", "Adjetivo", "ADJETIVO", "Adjetivo-Coloquial", "Adjetivo ", "Adjetivo - N", "adjetivo/sustantivo", "Adjetivo/sustantivo", "Adjetivp", "gentilicio", "Gentilicio", "Gentilicio"],
    },
    "Enciclopédica": {
        "escritura_erronea": [
            "enciclo",
            "Enciclo",
            "Enciclo- Ciencia",
            "Enciclo- cine/musica",
            "Enciclo- deporte",
            "Enciclo- Deporte",
            "Enciclo- Historia",
            "Enciclo- literatura",
            "Enciclo- Miscelanea",
            "Enciclo- mit",
            "Enciclo- Mitología",
            "Enciclo- TV",
            "Enciclo-arte",
            "Enciclo-Ciencia",
            "Enciclo-Cine",
            "Enciclo-Cine/musica",
            "Enciclo-Cs",
            "Enciclo-Cs Naturales",
            "Enciclo-Geo",
            "Enciclo-Geografía",
            "Enciclo-Historia",
            "Enciclo-lit",
            "Enciclo-Lit",
            "ENCICLO-LIT",
            "Enciclo-literatura",
            "Enciclo-Literatura",
            "Enciclo-Musica",
            "Enciclo-Música",
            "Enciclo-Religion",
            "Enciclo-TV",
            "Enciclo - Arte",
            "Enciclo - Deportes",
            "Enciclo - Literatura",
            "Enciclo - Mitología",
            "Enciclo - Música",
            "Enciclo – Cine",
            "Enciclo – Deporte",
            "Enciclo – Historia",
            "Enciclo – TV",
            "Enciclo . Geo",
            "ENCICLO CINE Y TV",
            "Enciclo Historia",
            "Enciclo Miscel",
            "Encicloédica-Deporte",
            "Enciclopedia ",
            "ENCICLOPEDIA - cine y tv",
            "Enciclopedia – Música",
            "enciclopedica",
            "Enciclopedica",
            "ENCICLOPEDICA",
            "enciclopédica",
            "Enciclopédica",
            "Enciclopédica- Cs naturales",
            "Enciclopédica- deporte",
            "Enciclopédica- Geografía",
            "Enciclopédica- Historia",
            "Enciclopédica- Literatura",
            "Enciclopédica- Música",
            "Enciclopédica-Cine",
            "Enciclopédica-Geografía",
            "Enciclopédica-Misceláneas",
            "Enciclopédica-Música",
            "Enciclopédica-N",
            "ENCICLOPÉDICA-N",
            "Enciclopedica ",
            "Enciclopédica ",
            "Enciclopédica -  Cine y TV",
            "Enciclopédica -  Geografía",
            "ENCICLOPÉDICA -  GEOGRAFÍA",
            "Enciclopédica -  Historia",
            "Enciclopédica -  Miscelaneas",
            "Enciclopédica -  Mitología y Religión",
            "Enciclopédica - Arte",
            "Enciclopédica - ARTE",
            "Enciclopédica - Ciencia",
            "Enciclopédica - CINE",
            "Enciclopedica - cine y tv",
            "ENCICLOPEDICA - cine y tv",
            "Enciclopédica - Cine y tv",
            "Enciclopédica - Cine y tV",
            "Enciclopédica - Cine y TV",
            "Enciclopédica - CINE Y TV",
            "Enciclopédica - Deporte",
            "Enciclopédica - DEPORTE",
            "Enciclopédica - Deporte. o Relat.",
            "Enciclopédica - Deportes",
            "Enciclopédica - Filosofia",
            "Enciclopédica - Filosofía",
            "Enciclopédica - geografía",
            "Enciclopédica - Geografía",
            "Enciclopédica - GEOGRAFÍA",
            "Enciclopédica - Historia",
            "Enciclopédica - HISTORIA",
            "Enciclopedica - literatura",
            "Enciclopédica - literatura",
            "Enciclopédica - Literatura",
            "Enciclopédica - LITERATURA",
            "Enciclopedica - miscelanea",
            "Enciclopedica - Miscelanea",
            "Enciclopédica - miscelánea",
            "Enciclopédica - Miscelánea",
            "Enciclopédica - Miscelaneas",
            "Enciclopédica - Misceláneas",
            "Enciclopédica - Mitología",
            "Enciclopédica - MITOLOGÍA",
            "Enciclopédica - Mitología y religión",
            "Enciclopédica - Mitología y Religión",
            "Enciclopédica - Música",
            "Enciclopédica - MÚSICA",
            "Enciclopédica - N",
            "Enciclopédica - Religión",
            "Enciclopédica – Cine",
            "Enciclopedica – Cine y TV",
            "Enciclopédica – Deporte",
            "Enciclopédica – Geografía",
            "Enciclopédica – Literatura",
            "Enciclopédica – LITERATURA",
            "Enciclopédica – Mitología",
            "Enciclopédica – Música",
            "Enciclopédica – TV y cine",
            "ENCICLOPEDICA CINE",
            "Enciclopédica Cine",
            "Enciclopédica Cine y TV",
            "Enciclopedica Geografia",
            "Enciclopédica Geografía",
            "Enciclopedica Literatura",
            "Enciclopédica Literatura",
            "Encicopédica",
            "Encilo- Cine",
            "Encilo- Miscelanea",
            "Encliclo - Geo",
            "Encliclo Musica",
        ],
        "comienzo_acepcion": [
            "Apellido de ", "Apellido del", "Nombre de ", "Nombre del", "Ciudad donde"
        ]
    },
    "Pert. O Relat.": {
        "escritura_erronea": [
            "Perneciente o Relativo",
            "pert o rel",
            "Pert o rel",
            "Pert o rel ",
            "Pert o relat",
            "Pert o Relat",
            "Pert o relati vo",
            "pert o relativo",
            "Pert o relativo",
            "pert o relativo ",
            "Pert o relativo ",
            "Pert o Releativo",
            "Pert. o rel.",
            "Pert. o Rel.",
            "Pert. O Rel.",
            "Pert. O Relat",
            "Pert. o relat.",
            "Pert. o Relat.",
            "Pert. O relat.",
            "Pert. O Relat.",
            "Pert. o Relat. ",
            "Pert. o relativo",
            "Pert. o Relativo",
            "Pert. o relativo ",
            "Pert. Relat.",
            "Pert. y relativo",
            "pert.o relativo",
            "Pert.o relativo",
            "pert.y relativo",
            "Pert/rel",
            "Perteciente o Relativo",
            "Perteneciene o Relativo",
            "perteneciente o relativo",
            "Perteneciente o relativo",
            "Perteneciente o Relativo",
            "Perteneciente y relativo",
            "Perteneciete o Relativo",
            "PyR",
        ],
        "comienzo_acepcion": ["Perteneciente o relativo a", "Relativo a", "Perteneciente a"],
    },
    "Sustantivo": {
        "escritura_erronea": [
            "fem",
            "fem/masc",
            "femenino",
            "Femenino",
            "FemenINO",
            "FemENINO",
            "FEMENINO",
            "Femenino- coloq",
            "Femenino ",
            "Femenino - N",
            "Femenino coloq",
            "masc",
            "Masc-Coloq",
            "masc-fem",
            "Masc-fem",
            "Masc-Fem",
            "Masc-Fem - N",
            "Masc-femenino",
            "Masc - fem",
            "Masc - Fem",
            "MASC - Fem",
            "masc fem",
            "Masc fem",
            "Masc.-fem.",
            "Masc. Fem. - N",
            "masc/fem",
            "Masc/fem",
            "Mascuino",
            "masculino",
            "Masculino",
            "MASculino",
            "MASCUlino",
            "MASCULINO",
            "Masculino-femenino",
            "Masculino-Femenino",
            "Masculino-femenino/ Masculino",
            "Masculino ",
            "Masculino - femenino",
            "Masculino - N",
            "Masculino /Femenino",
            "Masculino Femenino",
            "masculino y femenino",
            "Masculino y femenino",
            "Masculino y Femenino",
            "Masculino/Femenino",
            "Plural",
            "Plural fem",
            "Sust. Fem.",
            "Sust. Masc.",
            "sustantivo",
            "Sustantivo",
            "SUSTANTIVO",
            "Sustantivo ",
            "Sustantivo (M y F)",
            "Sustantivo (M Y F)",
        ]
    },
    "Verbo": {
        "escritura_erronea": [
            "intansitivo",
            "intr",
            "intransitivo",
            "Intransitivo",
            "Intransitivo ",
            "Intransitivo/Prnominal",
            "Intransitivo/Pronominal",
            "intrasitivo",
            "Intrasitivo",
            "transitivo",
            "Transitivo",
            "Transitivo - N",
            "Transitivo/Pronominal",
            "Verb. Intr.",
            "Verb. Trans.",
            "verbo",
            "Verbo",
            "Verbo Prnl.",
        ]
    }
}


LETTERS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "L", "M", "N", "Ñ", "O", "P", "Q", "R", "S", "T", "U", "V", "X", "Y", "Z"]
LETTERS_CONTAINS = ["H", "J", "Ñ", "Q", "U", "X", "Y", "Z"]

VOWELS = {
    "A": ["A", "Á"],
    "E": ["E", "É"],
    "I": ["I", "Í"],
    "O": ["O", "Ó"],
    "U": ["U", "Ú", "Ü"],
}

EXCEL_CELLS = {
    "columns": {
        "aception": "C",
        "answer": "D",
        "word_category": "E",
        "also_valid": "F",
        "not_valid": "G",
        "right_answers": "Y",
    },
    "rows": {
        letter: row
        for row, letter in enumerate(LETTERS, start=2)
    }
}